# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  assemble:
    docker:
      # specify the version you desire here
      - image: circleci/node:11-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests before deploy and docker build.
      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Assemble project
          command: npm run build

  image:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: project-dist-{{ .Revision }}
      - run:
          name: Build container
          command: docker build -t spacetabs/vue-components:latest .
      - run:
          name: Login to the docker hub
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run:
          name: Push image to registry
          command: docker push spacetabs/vue-components:latest

  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: project-dist-{{ .Revision }}
      - run:
          name: Deploy the app
          command: |
            wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
            heroku plugins:install heroku-container-registry
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web --app $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_push:
    jobs:
      - assemble
      - image:
          requires:
            - assemble
      - deploy:
          requires:
            - assemble
            - image
