# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy the app
          command: |
            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web --app $HEROKU_APP_NAME
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  version: 2
  release_app:
    jobs:
      - deploy
